import { styled } from "../../theme";

export const Button = styled("button", {
  cursor: "pointer",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  gap: "8px",
  backgroundColor: "$black",
  border: "none",
  outline: "none",
  fontFamily: "$sans",
  fontWeight: "$regular",
  fontSize: "$sm",
  transition: "background-color 300ms ease",

  variants: {
    variant: {
      counter: {
        width: "2rem",
        height: "2rem",
        backgroundColor: "$white",
        border: "1px solid $gray200",
        borderRadius: "0.4rem",

        "&:hover": {
          backgroundColor: "$gray100",
        },
      },
      text: {
        width: "15rem",
        height: "4.5rem",
        backgroundColor: "$primary20",
        padding: "8px 0",
        color: "$white",
        textTransform: "uppercase",
        "&:hover": {
          backgroundColor: "$primary1",
        },
      },
      brand: {
        color: "$white",
        backgroundColor: "$primary20",
        border: "1px solid $primary30",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        padding: "8px 42px",
        height: "4rem",
        textTransform: "uppercase",
        "&:hover": {
          backgroundColor: "$gray100",
          border: "1px solid $primary10",
          color: "$primary20",
        },
      },
      social: {
        color: "$white",
        backgroundColor: "$primary500",
        border: "1px solid $primary500",
        display: "grid",
        gridTemplateColumns: "0.5fr 5.5fr 0.5fr",
        gap: "1rem",
        height: "4rem",
        textTransform: "uppercase",
        textAlign: "center",
        img: {
          width: "3.8rem",
        },
        "&:hover": {
          backgroundColor: "$white",
          border: "1px solid $primary500",
          color: "$primary500",
        },
      },
      outline: {
        color: "$primary500",
        backgroundColor: "$white",
        border: "1px solid $primary500",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        padding: "8px 42px",
        height: "4rem",
        textTransform: "uppercase",
        "&:hover": {
          backgroundColor: "$primary500",
          border: "1px solid $primary500",
          color: "$white",
        },
      },
      disable: {
        color: "$white",
        backgroundColor: "$gray200",
        border: "1px solid $white",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        padding: "8px 42px",
        height: "4rem",
        textTransform: "uppercase",
        cursor: "not-allowed",
        opacity: "0.8",
        "@desktop": {
          width: "90%",
        },
      },
      simple: {
        width: "13rem",
        color: "$gray900",
        border: "1px solid $gray500",
        display: "flex",
        justifyContent: "start",
        alignItems: "center",
        paddingLeft: "2rem",
        height: "3.2rem",
        textTransform: "uppercase",
        opacity: "0.8",
        fontSize: "$xs",
      },
      rounded: {
        width: "15rem",
        color: "$white",
        border: "2px solid $white",
        borderRadius: "5rem",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        fontWeight: "bold",
        height: "3rem",
        textTransform: "uppercase",
        "&:hover": {
          backgroundColor: "$white",
          border: "1px solid $white",
          color: "$gray500",
        },
      },
      link: {
        padding: "8px 0",
        color: "$primary500",
        textDecoration: "underline",
      },
    },
    size: {
      small: {
        fontSize: "$xxs",
        padding: "4px 24px",
        height: "3rem",
      },
    },
  },
});
